# Generated by Django 6.0.3 on 2026-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('pizza', 'Пиццы'), ('soup', 'Супы'), ('salad', 'Салаты'), ('drinks', 'Напитки'), ('desserts', 'Десерты')], default='pizza', max_length=50),
        ),
    ]
